# Generated by Django 4.1 on 2023-09-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_rate', models.PositiveIntegerField(default=15, help_text='Refresh rate (in minutes).')),
            ],
            options={
                'verbose_name_plural': 'Config',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
